spring:
  config:
    activate:
      on-profile: production
  server:
    port: 8080 # to update
  datasource:
    url: jdbc:postgresql://postgres-db.cjqt4bf02oy9.ap-northeast-2.rds.amazonaws.com:5432/crmdb
    username: crmdbadmin # to update
    password: ${DB_PASSWORD} # to update
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_ya55bZ0sg