spring:
  config:
    activate:
      on-profile: production
  server:
    port: 8080 # to update
  logging:
    config: classpath:logback-production.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/crmdatabase # to update
    username: crmappuser # to update
    password: crmapppassword # to update
    driver-class-name: org.postgresql.Driver


aws:
  endpoint:
    url: http://localstack:4566
  region: ap-southeast-1
  logs:
    logGroupName: crm-logs
    logStreamName: crm-log-stream