spring:
  application:
    name: crm
  server:
    port: 8080
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
      com.itsag3t1.crm: DEBUG
  datasource:
    url: jdbc:postgresql://localhost:5432/crmdatabase
    username: crmappuser
    password: crmapppassword
    driver-class-name: org.postgresql.Driver