services:
  app:
    image: crm-app
    container_name: crm_app
    build:
      context: .
      dockerfile: Dockerfile-local-package
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - CLOUDWATCH_URI=http://localstack:4566

  db:
    image: postgres:16
    container_name: crm_db
    environment:
      POSTGRES_DB: crmdatabase
      POSTGRES_USER: crmappuser
      POSTGRES_PASSWORD: crmapppassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: