services:
  app:
    image: crm-app
    container_name: crm_app
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: crm_db
    environment:
      POSTGRES_DB: crmdb
      POSTGRES_USER: crmappuser
      POSTGRES_PASSWORD: crmapppassword
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#      - ./dbsetup/dbseed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  db_data: