services:
  app:
    image: crm-app
    container_name: crm_app
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - CLOUDWATCH_URI=http://localstack:4566
      - AWS_ACCESS_KEY=test
      - AWS_KEY_ID=test

  db:
    image: postgres:16
    container_name: crm_db
    environment:
      POSTGRES_DB: crmdatabase
      POSTGRES_USER: crmappuser
      POSTGRES_PASSWORD: crmapppassword
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=logs,ses
      - DEFAULT_REGION=ap-southeast-1
    volumes:
      - ./localstack/cloudwatch.sh:/docker-entrypoint-initaws.d/cloudwatch.sh

volumes:
  db_data: