apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itsag3t1-crm
  name: itsag3t1-crm-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: itsag3t1-crm-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: itsag3t1-crm-backend
    spec:
      containers:
      - image: public.ecr.aws/t2p9h2o6/itsag3t1/backend:b6bafca9cb653a5f65d903e6929696b65fa209b3
        name: itsag3t1-crm-backend
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: DB_HOSTNAME
            value: "my-primary-db.crcwuko4kdlb.ap-southeast-1.rds.amazonaws.com"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "crmdb"
          - name: DB_USERNAME
            value: "crmdbadmin"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-crm-password
                key: crm_db_password
---
apiVersion: v1
kind: Service
metadata:
  namespace: itsag3t1-crm
  name: itsag3t1-crm-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: itsag3t1-crm-backend