apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itsag3t1-crm-ingress
  namespace: itsag3t1-crm
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.itsag3t1.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Accept, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "http-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_500 http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: www.itsag3t1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: itsag3t1-crm-frontend
                port:
                  name: http
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: itsag3t1-crm-backend
                port:
                  name: http
          - path: /transaction
            pathType: Prefix
            backend:
              service:
                name: itsag3t1-crm-backend-feature4
                port:
                  name: http