apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itsag3t1-crm
  name: itsag3t1-crm-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: itsag3t1-crm-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: itsag3t1-crm-backend
    spec:
      containers:
      - image: public.ecr.aws/t2p9h2o6/itsag3t1/backend:4838a432ab5c40ea16c53cf5fc13dd17ff487011
        name: itsag3t1-crm-backend
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-crm-password
                key: crm_db_password
---
apiVersion: v1
kind: Service
metadata:
  namespace: itsag3t1-crm-backend
  name: itsag3t1-crm-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: itsag3t1-crm-backend