apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore-sm
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: itsag3t1-crm
  name: external-secrets-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  target:
    name: db-crm-password
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: crm_db_password
      remoteRef:
        key: db_password
