apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itsag3t1-crm-frontend-ingress
  namespace: itsag3t1-crm
spec:
  ingressClassName: nginx
  rules:
    - host: www.itsag3t1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: itsag3t1-crm-frontend
                port:
                  name: http