apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: itsag3t1-crm
  name: itsag3t1-crm-backend-feature4-hpa
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: itsag3t1-crm-backend-feature4
  targetCPUUtilizationPercentage: 80