apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itsag3t1-crm
  name: itsag3t1-crm-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: itsag3t1-crm-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: itsag3t1-crm-frontend
        app: frontend
    spec:
      nodeSelector:
        type: karpenter
      terminationGracePeriodSeconds: 0
      containers:
      - image: public.ecr.aws/t2p9h2o6/itsag3t1/frontend:d1928156dde67d3c11d9b6530ee8af8edd4762c0
        name: itsag3t1-crm-frontend
        env:
          - name: VITE_APP_VERSION
            value: v1.3.0
          - name: GENERATE_SOURCEMAP
            value: "false"
          - name: PUBLIC_URL
            value: "https://dashboard.io/home"
          - name: VITE_APP_BASE_NAME
            value: "/home"
          - name: VITE_ENV
            value: "production"
          - name: VITE_AWS_REGION
            value: "ap-southeast-1"
          - name: VITE_USER_POOL_ID
            value: "ap-southeast-1_ya55bZ0sg"
          - name: VITE_CLIENT_ID
            value: "46d0ev383r0i600e39nh43k9ac"
          - name: VITE_AWS_ACCESS_KEY_ID
            value: "AKIAVD3BDD5QBC4X7FU2"
          - name: VITE_AWS_SECRET_ACCESS_KEY
            value: "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"
        resources:
          limits:
            cpu: 1000m
        ports:
        - containerPort: 3000
          name: http
      topologySpreadConstraints:
#        - labelSelector:
#            matchLabels:
#              app: frontend
#          maxSkew: 1
#          topologyKey: kubernetes.io/hostname
#          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app: frontend
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
---
apiVersion: v1
kind: Service
metadata:
  namespace: itsag3t1-crm
  name: itsag3t1-crm-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: itsag3t1-crm-frontend
